### ISSUE TITLE
doesn't work properly with a 600 string, gen 2.

### ISSUE THREAD

**Issue by JLOrwell** [MarkAlanJones/TwinklyWPF#1]
I'm looking into this myself, but I've successfully tested this on multiple 100 and 250 strings.  The 600 shows that it goes into rt mode but never changes when the frames are being sent to it.

**Comment by BioeJD** [comment]
> 

I'm looking at grabbing a 600 light set myself, but I'm worried they aren't gonna work for sending frames to. Did you ever come to a solution here?

**Comment by JLOrwell** [comment]
check out my program at artnet2twinkly.com.  I did get it working.  The problem is this repository didn't support the gen 3 frames than all their new devices use.  The devices are all backwards compatible with gen 2 frames but those frames aren't big enough to fit 600 leds in.  If you're writing something yourself, you should google xled read the docs.  Scan it for info on how the frames work.

This project here is a good way to get your feet wet with twinkly control, but it's by no means fully functional.  Even the device finder is broken and will only detect the first device that responds.  If you are simply wanting to expand what you can do with the twinkly lights, join the twinkly (unofficial) users group on facebook.  A few of us maintain programs on there.  I have a light-show streaming client, and another guy, phuoc hua has a program that allows you to use gifs as sequences.

**Comment by BioeJD** [comment]
Thanks! Great, I actually did come across your project while I was researching. I ended up getting the 600 light string. I would love to join the groups and contribute as well.

**Comment by MarkAlanJones** [comment]
RT supports frame version 3 (chunks of 900) now ... but it has had very limited testing

**Comment by JLOrwell** [comment]
have you done any work on getting it to respond to more than just the first device?

**Comment by MarkAlanJones** [comment]
No, because I only have one set out right now 😉

I was thinking a drop down of the detected ones – so still one at a time
but I guess you could run multiple copies…

Otherwise a Tab per device ?

If you are trying to just use the API – I suspect each instance could take an IP address.
what does it do if the lights are off at that ip, keep retrying until it comes on line ?

I noticed that a lot more of the API is documented now, so I am missing functional coverage
…not even sure what all of it does.

- Mark Jones

**Comment by MarkAlanJones** [comment]
Latest Changes add support for multiple twinklys on the network

- Mark Jones
